apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-public
spec:
  type: LoadBalancer
  selector:
    name: grafana
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080